spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#      settings:
#        web-allow-others: true
#  datasource:
#    url: jdbc:h2:mem:test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties: # 예쁘게 보기
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger ??
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
admin:
  email:
    ggammancj@gmail.com
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket:
        mentor-bucket: ${AWS_MENTOR_BUCKET}
        profile-bucket: ${AWS_PROFILE_BUCKET}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false